// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA0LiChVZJ53kWQfP-EbHRVKpEcuJGSwk',
    appId: '1:934295179369:web:40c77d4e661e72650c92f8',
    messagingSenderId: '934295179369',
    projectId: 'ewaste-b5ba9',
    authDomain: 'ewaste-b5ba9.firebaseapp.com',
    storageBucket: 'ewaste-b5ba9.firebasestorage.app',
    measurementId: 'G-NPB1ZNV1WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhy6qOtKK3U9n_SBFvGTOtm1xLsleg3Xw',
    appId: '1:934295179369:android:c89527f2be9ce5300c92f8',
    messagingSenderId: '934295179369',
    projectId: 'ewaste-b5ba9',
    storageBucket: 'ewaste-b5ba9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpoHMGGMa0DujMqxi8hxKtbzQy7VbUAM8',
    appId: '1:934295179369:ios:8f38fa43cc1931e80c92f8',
    messagingSenderId: '934295179369',
    projectId: 'ewaste-b5ba9',
    storageBucket: 'ewaste-b5ba9.firebasestorage.app',
    iosBundleId: 'com.example.ewaste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpoHMGGMa0DujMqxi8hxKtbzQy7VbUAM8',
    appId: '1:934295179369:ios:8f38fa43cc1931e80c92f8',
    messagingSenderId: '934295179369',
    projectId: 'ewaste-b5ba9',
    storageBucket: 'ewaste-b5ba9.firebasestorage.app',
    iosBundleId: 'com.example.ewaste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA0LiChVZJ53kWQfP-EbHRVKpEcuJGSwk',
    appId: '1:934295179369:web:275cfce09e0f12cd0c92f8',
    messagingSenderId: '934295179369',
    projectId: 'ewaste-b5ba9',
    authDomain: 'ewaste-b5ba9.firebaseapp.com',
    storageBucket: 'ewaste-b5ba9.firebasestorage.app',
    measurementId: 'G-29L6VL52YN',
  );
}
